package cs.c301.project;

import java.util.Vector;
import cs.c301.project.Data.PhotoEntry;
import cs.c301.project.Listeners.PhotoModelListener;


/**
 * ComparePhotoView allows the user to see and compare different
 * photos. Currently used as a place holder 
 *
 */
public class ComparePhotoView implements PhotoModelListener {

	/**
	 * Autogenerated by the model listener. Place holder.
	 */
	public void photosChanged(Vector<PhotoEntry> photos) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * Autogenerated by the model listener. Place holder.
	 */
	public void tagsChanged(Vector<String> tags) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * Autogenerated by the model listener. Place holder.
	 */
	public void groupsChanged(Vector<String> groups) {
		// TODO Auto-generated method stub
		
	}

}
